# Generated by Django 4.2.26 on 2026-03-19 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=300)),
                ('company_logo_url', models.URLField(blank=True)),
                ('job_title', models.CharField(max_length=300)),
                ('job_description', models.TextField()),
                ('work_type', models.CharField(choices=[('full_time', 'Full Time'), ('internship', 'Internship'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('remote', 'Remote')], default='full_time', max_length=20)),
                ('experience_level', models.CharField(choices=[('fresher', 'Fresher / 0-1 years'), ('junior', 'Junior / 1-3 years'), ('mid', 'Mid Level / 3-5 years'), ('senior', 'Senior / 5+ years')], default='fresher', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_remote', models.BooleanField(default=False)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('required_skills', models.JSONField(default=list)),
                ('preferred_skills', models.JSONField(blank=True, default=list)),
                ('minimum_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('eligible_branches', models.JSONField(blank=True, default=list)),
                ('eligible_graduation_years', models.JSONField(blank=True, default=list)),
                ('apply_link', models.URLField(blank=True)),
                ('max_applicants', models.IntegerField(default=5)),
                ('total_applications', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('closed', 'Closed — All slots filled'), ('deactivated', 'Deactivated by Admin'), ('paused', 'Paused by Author')], default='active', max_length=20)),
                ('deadline', models.DateTimeField()),
                ('is_urgent', models.BooleanField(default=False)),
                ('is_boosted', models.BooleanField(default=False)),
                ('boosted_until', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_boosted', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('rejected', 'Rejected'), ('hired', 'Hired'), ('withdrawn', 'Withdrawn by Student')], default='applied', max_length=30)),
                ('match_score', models.IntegerField(default=0)),
                ('matched_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('is_faculty_recommended', models.BooleanField(default=False)),
                ('recommendation_note', models.TextField(blank=True)),
                ('cover_note', models.TextField(blank=True)),
                ('alumni_note', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_recommendations', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='referrals.referral')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_faculty_recommended', '-match_score', 'applied_at'],
                'unique_together': {('referral', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ReferralSuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=300)),
                ('job_title', models.CharField(max_length=300)),
                ('is_public', models.BooleanField(default=True)),
                ('testimonial', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_successes', to=settings.AUTH_USER_MODEL)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='success_story', to='referrals.referralapplication')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_stories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyReferralRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_recommendations', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_recommendations', to='referrals.referral')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_referral_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('faculty', 'student', 'referral')},
            },
        ),
    ]
