# Generated by Django 4.2.26 on 2026-03-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['status', '-created_at'], name='referrals_r_status_a5beca_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['posted_by', 'status'], name='referrals_r_posted__cc4599_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['deadline', 'status'], name='referrals_r_deadlin_307492_idx'),
        ),
    ]
