# Generated by Django 4.2.26 on 2026-03-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_add_db_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['work_type', 'status'], name='referrals_r_work_ty_c46a22_idx'),
        ),
    ]
