# Generated by Django 4.2.26 on 2026-03-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='bank_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='bank_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
