# Generated by Django 4.2.26 on 2026-03-22 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alumniprofile_bank_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='verification_document_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='verification_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('not_submitted', 'Not Submitted')], default='not_submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumni_verifications_done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='suspended_reason',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_verified', 'User Verified'), ('user_suspended', 'User Suspended'), ('user_unsuspended', 'User Unsuspended'), ('user_deleted', 'User Deleted'), ('post_hidden', 'Post Hidden'), ('post_deleted', 'Post Deleted'), ('post_approved', 'Post Approved'), ('session_cancelled', 'Session Cancelled'), ('referral_deactivated', 'Referral Deactivated'), ('payout_approved', 'Payout Approved'), ('payout_processed', 'Payout Processed'), ('payout_rejected', 'Payout Rejected'), ('alumni_verified', 'Alumni Profile Verified'), ('alumni_rejected', 'Alumni Verification Rejected'), ('broadcast_sent', 'Broadcast Notification Sent'), ('other', 'Other')], max_length=30)),
                ('target_object_type', models.CharField(blank=True, max_length=50)),
                ('target_object_id', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
