# Generated by Django 4.2.26 on 2026-04-19 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alumniprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultyprofile',
            old_name='subjects',
            new_name='subjects_taught',
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='available_for_sessions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='college_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='college_staff_page_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='google_scholar_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='languages_known',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='max_students_per_session',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='office_hours',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='personal_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='preferred_session_duration',
            field=models.CharField(choices=[('30', '30 minutes'), ('45', '45 minutes'), ('60', '60 minutes'), ('90', '90 minutes')], default='60', max_length=10),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='preferred_session_mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('both', 'Both')], default='online', max_length=10),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='profile_completeness_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='qualification_university',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='research_publications_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='researchgate_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='session_types_offered',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='soft_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='teaching_mode',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('visiting', 'Visiting Faculty'), ('guest', 'Guest Lecturer')], max_length=20),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='technical_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='tools_technologies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='years_of_experience',
            field=models.CharField(blank=True, choices=[('0-2', '0-2 years'), ('2-5', '2-5 years'), ('5-10', '5-10 years'), ('10-20', '10-20 years'), ('20+', '20+ years')], max_length=20),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
