# Generated by Django 4.2.29 on 2026-05-05 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_subjects_facultyprofile_subjects_taught_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumniprofile',
            options={'verbose_name': 'Alumni Profile'},
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='is_available_for_1on1',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='price_per_30min',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='price_per_60min',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='verification_document',
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='achievements',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='advice_for_students',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='available_for_mentorship',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='blog_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='branch',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='cgpa_or_percentage',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='college_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='current_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='degree',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='domain_expertise',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('freelance', 'Freelance / Consultant'), ('entrepreneur', 'Entrepreneur / Founder'), ('not_working', 'Not Currently Working')], max_length=20),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='is_open_to_opportunities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='languages_known',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='max_students_per_week',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='mentorship_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='preferred_session_duration',
            field=models.CharField(choices=[('30', '30 minutes'), ('45', '45 minutes'), ('60', '60 minutes'), ('90', '90 minutes')], default='60', max_length=10),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='preferred_session_mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('both', 'Both')], default='online', max_length=10),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='profile_completeness_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='session_price_range',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='soft_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='technical_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='tools_used',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='verification_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='years_of_experience',
            field=models.CharField(blank=True, choices=[('0-1', 'Fresher (0-1 years)'), ('1-3', '1-3 years'), ('3-5', '3-5 years'), ('5-10', '5-10 years'), ('10+', '10+ years')], max_length=20),
        ),
    ]
