# Generated by Django 4.2.26 on 2026-05-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_alumniprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
