databases:
  - name: alumniai-db
    databaseName: alumniai_db
    user: alumniai_user
    plan: free

services:
  - type: web
    name: alumniai-web
    env: python
    buildCommand: |
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput --settings=alumni_platform.settings.prod &&
      python manage.py migrate --settings=alumni_platform.settings.prod
    startCommand: daphne -b 0.0.0.0 -p $PORT alumni_platform.asgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: alumni_platform.settings.prod
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'False'
      - key: DATABASE_URL
        fromDatabase:
          name: alumniai-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: alumniai-redis
          type: redis
          property: connectionString
      - key: ALLOWED_HOSTS
        sync: false

  - type: redis
    name: alumniai-redis
    plan: free
    ipAllowList: []