# Generated by Django 4.2.26 on 2026-03-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_db_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payer', '-created_at'], name='payments_tr_payer_i_011ac7_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payee', '-created_at'], name='payments_tr_payee_i_3275e1_idx'),
        ),
    ]
