# Generated by Django 4.2.26 on 2026-05-06 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions_app', '0003_session_sessions_ap_host_id_3f6eb1_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referrals', '0003_referral_referrals_r_work_ty_c46a22_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRatingAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_total_ratings', models.IntegerField(default=0)),
                ('host_average_overall', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('host_average_communication', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('host_average_value', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('host_average_professionalism', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('host_would_recommend_pct', models.IntegerField(default=0)),
                ('host_five_star', models.IntegerField(default=0)),
                ('host_four_star', models.IntegerField(default=0)),
                ('host_three_star', models.IntegerField(default=0)),
                ('host_two_star', models.IntegerField(default=0)),
                ('host_one_star', models.IntegerField(default=0)),
                ('student_total_ratings', models.IntegerField(default=0)),
                ('student_average_overall', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('referral_total_ratings', models.IntegerField(default=0)),
                ('referral_average_overall', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_aggregate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('process_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('communication_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('review_text', models.TextField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='referrals.referralapplication')),
                ('ratee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_ratings_received', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_ratings_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_type', models.CharField(choices=[('student_to_host', 'Student Rating Host'), ('host_to_student', 'Host Rating Student')], max_length=20)),
                ('overall_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('communication_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('value_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('professionalism_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('would_recommend', models.BooleanField(blank=True, null=True)),
                ('review_text', models.TextField(blank=True, max_length=300)),
                ('preparation_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('engagement_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('punctuality_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('feedback_text', models.TextField(blank=True, max_length=200)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='sessions_app.booking')),
                ('ratee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ratee', 'rating_type'], name='ratings_ses_ratee_i_deee69_idx'), models.Index(fields=['ratee', 'overall_rating'], name='ratings_ses_ratee_i_e518e5_idx')],
                'unique_together': {('booking', 'rater')},
            },
        ),
    ]
