# Generated by Django 4.2.26 on 2026-03-18 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('cancelled_by_student', 'Cancelled by Student'), ('cancelled_by_host', 'Cancelled by Host'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('no_show', 'No Show')], default='pending_payment', max_length=30)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_free_demo', models.BooleanField(default=False)),
                ('platform_cut', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('host_share', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=200)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=200)),
                ('razorpay_signature', models.CharField(blank=True, max_length=500)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('refund_reason', models.TextField(blank=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-booked_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_start', models.DateTimeField()),
                ('slot_end', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot', to='sessions_app.booking')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slot_start'],
            },
        ),
        migrations.CreateModel(
            name='SessionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='sessions_app.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('group', 'Group Session'), ('one_on_one', '1:1 Session'), ('cohort', 'Cohort Bundle'), ('recorded', 'Recorded Session'), ('doubt', 'Doubt Clearing Class'), ('project', 'Project Guidance'), ('career', 'Career Path Guidance')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('niche', models.CharField(blank=True, max_length=200)),
                ('skills_covered', models.JSONField(default=list)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('total_sessions_in_bundle', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_free', models.BooleanField(default=False)),
                ('is_demo_eligible', models.BooleanField(default=True)),
                ('max_seats', models.IntegerField(default=10)),
                ('booked_seats', models.IntegerField(default=0)),
                ('meeting_link', models.URLField(blank=True)),
                ('recording_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live Now'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='sessions/thumbnails/')),
                ('tags', models.JSONField(default=list)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('platform_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('host_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('co_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_hosted_sessions', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='sessions_app.session'),
        ),
        migrations.AddField(
            model_name='booking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('session', 'student')},
        ),
    ]
