# Generated by Django 4.2.26 on 2026-03-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['status', 'scheduled_at'], name='sessions_ap_status_1d214f_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['host', 'status'], name='sessions_ap_host_id_3d0ef8_idx'),
        ),
    ]
