# Generated by Django 4.2.26 on 2026-03-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0002_add_db_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['host', '-created_at'], name='sessions_ap_host_id_3f6eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['session_type', 'status'], name='sessions_ap_session_70dea5_idx'),
        ),
    ]
