# Generated by Django 4.2.26 on 2026-03-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', '-created_at'], name='feed_post_status_288ad9_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', 'status'], name='feed_post_author__fff51a_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_type', 'status'], name='feed_post_post_ty_52481e_idx'),
        ),
    ]
