# Generated by Django 4.2.26 on 2026-05-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_post_feed_post_author__c854fa_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='session_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
