# Generated by Django 4.2.26 on 2026-05-06 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_referral_referrals_r_work_ty_c46a22_idx'),
        ('feed', '0004_post_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_posts', to='referrals.referral'),
        ),
    ]
