# Generated by Django 4.2.26 on 2026-05-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_post_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Post auto-hides after this datetime. Null = never expires.', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('hidden', 'Hidden by Admin'), ('deleted', 'Deleted'), ('flagged', 'Flagged for Review')], default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['expires_at'], name='feed_post_expires_22719c_idx'),
        ),
    ]
