# Generated by Django 4.2.26 on 2026-05-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_add_external_job_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaljobapplication',
            name='match_score',
            field=models.IntegerField(default=0),
        ),
    ]
